/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.Person;
import model.PersonProfile;
import ui.PersonProfile.PersonMngWorkAreaJPanel;

/**
 *
 * @author siddh
 */
public class MainJFrame extends javax.swing.JFrame {
     
    private PersonProfile personProfile ;

   

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        this.personProfile = new PersonProfile();
        
        genrateDemoData();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        topJPanel = new javax.swing.JPanel();
        btnPersonMngAction = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        topJPanel.setBackground(new java.awt.Color(204, 204, 204));
        topJPanel.setForeground(new java.awt.Color(255, 255, 255));
        topJPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnPersonMngAction.setBackground(new java.awt.Color(102, 102, 102));
        btnPersonMngAction.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnPersonMngAction.setForeground(new java.awt.Color(255, 255, 255));
        btnPersonMngAction.setText("Open Person Profile Work Area");
        btnPersonMngAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonMngActionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topJPanelLayout = new javax.swing.GroupLayout(topJPanel);
        topJPanel.setLayout(topJPanelLayout);
        topJPanelLayout.setHorizontalGroup(
            topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPersonMngAction, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1685, Short.MAX_VALUE))
        );
        topJPanelLayout.setVerticalGroup(
            topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topJPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnPersonMngAction)
                .addContainerGap(1005, Short.MAX_VALUE))
        );

        splitPane.setTopComponent(topJPanel);

        userProcessContainer.setBackground(new java.awt.Color(153, 153, 153));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPersonMngActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonMngActionActionPerformed

        // TODO add your handling code here:
        PersonMngWorkAreaJPanel panel = new PersonMngWorkAreaJPanel(userProcessContainer, personProfile);
        userProcessContainer.add("PersonMngWorkAreaJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnPersonMngActionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPersonMngAction;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel topJPanel;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables

private void genrateDemoData(){
    Person fPerson = personProfile.addPerson();
        fPerson.setFName("ngre");
        fPerson.setLName("Nanfr");
        fPerson.setAge(65);
        fPerson.setSsn(1234567678);
        fPerson.setAddress("78 bksdgn", "Unit 3", "Boston", "MA", 2119L, 67126712, "92 Bragdon", "Unit 3", "Boston", "MA", 2119L, 2971278);
        
        Person sPerson = personProfile.addPerson();
        sPerson.setFName("ibidf");
        sPerson.setLName("hjdf");
        sPerson.setAge(5);
        sPerson.setSsn(1234567890);
        sPerson.setAddress("963 hsg", "Unit 3", "Boston", "MA", 2119L, 67126652, "92 Bragdon", "Unit 3", "Boston", "MA", 2119L, 2971278);
        
        
        Person tPerson = personProfile.addPerson();
        tPerson.setFName("abi");
        tPerson.setLName("uie");
        tPerson.setAge(2);
        tPerson.setSsn(123456834);
        tPerson.setAddress("78 bksdgn", "Unit 3", "Boston", "MA", 2119L, 67126712, "92 Bragdon", "Unit 3", "Boston", "MA", 2119L, 2971278);
        
        Person frPerson = personProfile.addPerson();
        frPerson.setFName("sid");
        frPerson.setLName("w");
        frPerson.setAge(20);
        frPerson.setSsn(1567887353);
        frPerson.setAddress("78 bksdgn", "Unit 3", "Boston", "MA", 2119L, 67126712, "92 Bragdon", "Unit 3", "Boston", "MA", 2119L, 2971278);
        
         Person fiPerson = personProfile.addPerson();
        fiPerson.setFName("Varun");
        fiPerson.setLName("Nayyar");
        fiPerson.setAge(23);
        fiPerson.setSsn(123456875);
        fiPerson.setAddress("78 bksdgn", "Unit 3", "Boston", "MA", 2119L, 67126712, "92 Bragdon", "Unit 3", "Boston", "MA", 2119L, 2971278);
        
}
}
